version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - node
    networks:
      - node-network

  node:
    build: 
      context: node-app
    container_name: node
    volumes:
      - ./node-app:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - node-network
  
networks:
  node-network:
    driver: bridge
    